tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
brew "git"
brew "vim"
brew "zsh"
brew "jq"
brew "fzf"
brew "tmux"
cask "font-iosevka-nerd-font"
# cask "macvim"
cask "firefox"
cask "wine-stable"
